# NOTE: This file must use spaces. Travis won't read it otherwise.

# Opt-in to the new Travis infrastructure
sudo: false

language: node_js
node_js: stable

matrix:
  include:
    - script:
        - npm test -- --coverage
        - npx coveralls < ./coverage/lcov.info

    - script:
        - npm run prepublishOnly
        - PKG="$(npm pack)"
        - tar xz < "$PKG"
        - cd ./package
        - npm install
        - npx browserify@16 index.js > bundle.js
