import findDays from '../find-days'

test('turns the day abbreviations into a list of unambiguous days', () => {
	expect(findDays('M')).toEqual(['Mo'])
	expect(findDays('T')).toEqual(['Tu'])
	expect(findDays('W')).toEqual(['We'])
	expect(findDays('Th')).toEqual(['Th'])
	expect(findDays('F')).toEqual(['Fr'])
})

test('handles hyphenated day sequences', () => {
	expect(findDays('M-F')).toEqual(['Mo', 'Tu', 'We', 'Th', 'Fr'])
	expect(findDays('M-Th')).toEqual(['Mo', 'Tu', 'We', 'Th'])
	expect(findDays('T-F')).toEqual(['Tu', 'We', 'Th', 'Fr'])
	expect(findDays('M-T')).toEqual(['Mo', 'Tu'])
})

test('handles strings of letters correctly', () => {
	expect(findDays('MTThFW')).toEqual(['Mo', 'Tu', 'Th', 'Fr', 'We'])
	expect(findDays('MTTh')).toEqual(['Mo', 'Tu', 'Th'])
	expect(findDays('ThFMT')).toEqual(['Th', 'Fr', 'Mo', 'Tu'])
})

test('correctly parses every variant that the SIS contains', () => {
	expect(findDays('F')).toEqual(['Fr'])
	expect(findDays('M')).toEqual(['Mo'])
	expect(findDays('M-F')).toEqual(['Mo', 'Tu', 'We', 'Th', 'Fr'])
	expect(findDays('M-Th')).toEqual(['Mo', 'Tu', 'We', 'Th'])
	expect(findDays('MF')).toEqual(['Mo', 'Fr'])
	expect(findDays('MFW')).toEqual(['Mo', 'Fr', 'We'])
	expect(findDays('MT')).toEqual(['Mo', 'Tu'])
	expect(findDays('MTF')).toEqual(['Mo', 'Tu', 'Fr'])
	expect(findDays('MTTh')).toEqual(['Mo', 'Tu', 'Th'])
	expect(findDays('MTThF')).toEqual(['Mo', 'Tu', 'Th', 'Fr'])
	expect(findDays('MTThFW')).toEqual(['Mo', 'Tu', 'Th', 'Fr', 'We'])
	expect(findDays('MTW')).toEqual(['Mo', 'Tu', 'We'])
	expect(findDays('MTWF')).toEqual(['Mo', 'Tu', 'We', 'Fr'])
	expect(findDays('MTh')).toEqual(['Mo', 'Th'])
	expect(findDays('MW')).toEqual(['Mo', 'We'])
	expect(findDays('MWF')).toEqual(['Mo', 'We', 'Fr'])
	expect(findDays('MWFT')).toEqual(['Mo', 'We', 'Fr', 'Tu'])
	expect(findDays('MWTh')).toEqual(['Mo', 'We', 'Th'])
	expect(findDays('MWThF')).toEqual(['Mo', 'We', 'Th', 'Fr'])
	expect(findDays('T')).toEqual(['Tu'])
	expect(findDays('T-F')).toEqual(['Tu', 'We', 'Th', 'Fr'])
	expect(findDays('TTh')).toEqual(['Tu', 'Th'])
	expect(findDays('TThF')).toEqual(['Tu', 'Th', 'Fr'])
	expect(findDays('TW')).toEqual(['Tu', 'We'])
	expect(findDays('TWF')).toEqual(['Tu', 'We', 'Fr'])
	expect(findDays('TWTh')).toEqual(['Tu', 'We', 'Th'])
	expect(findDays('Th')).toEqual(['Th'])
	expect(findDays('W')).toEqual(['We'])
	expect(findDays('WF')).toEqual(['We', 'Fr'])
	expect(findDays('WTh')).toEqual(['We', 'Th'])
})
